#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width            2
bspc config window_gap              5
bspc config bottom_padding          25

bspc config click_to_focus          button1
bspc config pointer_modifier        mod1

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
